
name: GH Demo

on:
  push:

jobs:
  demo:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Get Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: https://vault-plus-public-vault-8c8c1dfb.4ad44770.z1.hashicorp.cloud:8200
          role: gh-demo
          method: jwt
          path: gha
          secrets: |
            hcp/data/creds hcp_client_id | HCP_CLIENT_ID