name: Example
on:
  push:

jobs:
  action:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
          url: https://vault-plus-public-vault-8c8c1dfb.4ad44770.z1.hashicorp.cloud:8200
          method: jwt
          role: packer-action
          namespace: admin
          jwtGithubAudience: sigstore
          path: gha
          secrets: |
            secrets/data/gha test | GHA_TEST
# jobs:
  curl:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - run: sleep 5 # there's still a race condition for now
      - run: |
          OIDC_TOKEN=$(curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=o6s" -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN")

      - name: Get JWT Token
        run: |
          VAULT_JWT=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sigstore" | jq -r '.value')
          echo VAULT_JWT=$VAULT_JWT >> $GITHUB_ENV
          echo $VAULT_JWT
      - name: Authenticate to Vault
        run: |
          curl --request POST --data "{ \"jwt\": \"${{ env.VAULT_JWT }}\", \"role\": \"packer-action\"}" ${{ secrets.VAULT_ADDR }}/v1/auth/gha/login 