name: ubuntu-20-packer
on: [push] 

jobs:
  secrets-prebuild:
    runs-on: ubuntu-latest
    name: vault
    steps:
      - name: 
        id: vault-secrets
        uses: hashicorp/vault-action@v2.3.1
        with:
            url: ${{ secrets.VAULT_ADDR }}
            token: ${{ secrets.VAULT_TOKEN }}
            namespace: ${{ secrets.VAULT_NAMESPACE}}
            secrets: |
              hcp/packer hcp_client_secret | HCP_CLIENT_SECRET ;
              hcp/packer hcp_client_id | HCP_CLIENT_ID
  ubuntu-20-build:
    runs-on: ubuntu-latest
    name: packer
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      #authenticate to google cloud
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        #Move to Vault
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: .
        env:
        # Secrets placed here to scope to Build Step
        # Move to Vault KV
            HCP_CLIENT_SECRET: '${{ jobs.vault.steps.vault-secret.HCP_CLIENT_SECRET }}'
            HCP_CLIENT_ID: '${{ jobs.vault.steps.vault-secret.HCP_CLIENT_ID }}'   
      - run: echo "Packer status is ${{ job.status }}."