name: ubuntu-20-packer
on: [push] 

jobs:
#``HCP_PACKER_BUILD_FINGERPRINT=${{ env.GITHUB_SHA }}-${{ env.GITHUB_RUN_ID }}-${{ env.GITHUB_RUN_ATTEMPT}}""${{ env.GITHUB_SHA }}-${{ env.GITHUB_RUN_ID }}-${{ env.GITHUB_RUN_ATTEMPT}}
  ubuntu-20-build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    name: packer
    # needs: vault
    steps:
      - name: GIT_SHA_SHORT
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: 
        id: vault-secrets
        uses: hashicorp/vault-action@v2.3.1
        with:
            url: ${{ secrets.VAULT_ADDR }}
            token: ${{ secrets.VAULT_TOKEN }}
            namespace: ${{ secrets.VAULT_NAMESPACE}}
            secrets: |
              hcp/data/packer hcp_client_secret | HCP_CLIENT_SECRET ;
              hcp/data/packer hcp_client_id | HCP_CLIENT_ID ;
              aws/data/creds aws_access_key_id | AWS_ACCESS_KEY_ID ;
              aws/data/creds aws_secret_access_key | AWS_SECRET_ACCESS_KEY ;
              aws/data/creds aws_session_token | AWS_SESSION_TOKEN;
              gcp/data/creds google_credentials | GOOGLE_CREDENTIALS
      - name: Check out repository code
        uses: actions/checkout@v2
      #authenticate to google cloud
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        #Move to Vault
        with:
          credentials_json: '${{ steps.vault-secrets.outputs.google_credentials }}'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ steps.vault-secrets.outputs.aws_access_key_id }}
          aws-secret-access-key: ${{ steps.vault-secrets.outputs.aws_secret_access_key }}
          aws-session-token: ${{ steps.vault-secrets.outputs.aws_session_token }}
          aws-region: ap-southeast-2
          role-duration-seconds: 1200
          role-session-name: packer-gha
      - name: Build Artifact
        # uses: hashicorp/packer-github-actions@master
        uses: pandom/packer-github-actions@v0.3.1-ansible
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: .
        env:
        # # Secrets placed here to scope to Build Step
            HCP_PACKER_BUILD_FINGERPRINT: '${{ steps.vars.outputs.sha_short }}-${{ github.GITHUB_RUN_ID }}-${{ github.GITHUB_RUN_ATTEMPT }}'
            HCP_CLIENT_SECRET: '${{ steps.vault-secrets.outputs.hcp_client_secret }}'
            HCP_CLIENT_ID: '${{ steps.vault-secrets.outputs.hcp_client_id }}'      
      - run: echo "Packer status is a ${{ job.status }}."