name: ubuntu-20-packer
on: [push] 

jobs:
  # vault:
  #   runs-on: ubuntu-latest
  #   name: vault
  #   steps:
  #     - name: 
  #       id: secrets
  #       uses: hashicorp/vault-action@v2.3.1
  #       with:
  #           url: ${{ secrets.VAULT_ADDR }}
  #           token: ${{ secrets.VAULT_TOKEN }}
  #           namespace: ${{ secrets.VAULT_NAMESPACE}}
  #           secrets: |
  #             hcp/data/packer hcp_client_secret | HCP_CLIENT_SECRET ;
  #             hcp/data/packer hcp_client_id | HCP_CLIENT_ID
  #   outputs:
  #     hcp_client_secret: ${{ steps.secrets.outputs.HCP_CLIENT_SECRET }}
  #     hcp_client_id: ${{ steps.secrets.outputs.HCP_CLIENT_ID }}
  ubuntu-20-build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    name: packer
    # needs: vault
    steps:
      - name: 
        id: vault-secrets
        uses: hashicorp/vault-action@v2.3.1
        with:
            url: ${{ secrets.VAULT_ADDR }}
            token: ${{ secrets.VAULT_TOKEN }}
            namespace: ${{ secrets.VAULT_NAMESPACE}}
            secrets: |
              hcp/data/packer hcp_client_secret | HCP_CLIENT_SECRET ;
              hcp/data/packer hcp_client_id | HCP_CLIENT_ID
      - name: Check out repository code
        uses: actions/checkout@v2
      #authenticate to google cloud
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        #Move to Vault
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: .
        env:
        # # Secrets placed here to scope to Build Step
    
            # HCP_CLIENT_SECRET: '${{ needs.vault.outputs.hcp_client_secret }}'
            # HCP_CLIENT_ID: '${{ needs.vault.outputs.hcp_client_id }}'
            HCP_CLIENT_SECRET: '${{ steps.vault-secrets.outputs.hcp_client_secret }}'
            HCP_CLIENT_ID: '${{ steps.vault-secrets.outputs.hcp_client_id }}'      
      - run: echo "Packer status is a ${{ job.status }}."