name: ubuntu-20-packer
on: [push] 

jobs:
  ubuntu-20-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    name: packer
    steps:
      - name: retrieve-secrets
        id: vault-secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
            url: https://vault-plus-public-vault-8c8c1dfb.4ad44770.z1.hashicorp.cloud:8200
            namespace: admin
            jwtGithubAudience: sigstore
            method: jwt
            path: gha
            role: packer-action
            secrets: |
              hcp/data/creds hcp_client_secret | HCP_CLIENT_SECRET;
              hcp/data/creds hcp_client_id | HCP_CLIENT_ID
      - run: echo $HCP_CLIENT_ID